### ISSUE TITLE
Refractor

### ISSUE THREAD

**Issue by montogeek** [mrzmmr/unist-util-find-all-between#3]
Hey, sorry for opening an issue for a question.
I got a tree returned by: https://github.com/wooorm/refractor, but it doesn't have a root element.

How could I use this package with that kind of tree?

**Comment by montogeek** [comment]
It seems creating it works:
```js
const code = refractor.highlight(node.value, lang);

const newTree = {
   type: 'root',
   children: code
}

console.log(findAllBetween(newTree, summaryStart, summaryEnd ))
```

Where `summaryStart` and `summaryEnd` are nodes from `code`.

**Comment by mrzmmr** [comment]
Im not sure I understand the question but if `summaryStart` and `summaryEnd` are nodes in `newTree` then findAllBetween will work as advertised. ex

```js
var refractor = require('refractor')
var rehype = require('rehype')
var between = require('unist-util-find-all-between')
var find = require('unist-util-find')

var nodes = refractor.highlight('"use strict";\nvar a = "Hello"', 'js')

var parent = { type: 'root', children: nodes }

var start = find(parent, { children: [{ value: 'var' }] })
var end = parent.children[parent.children.length - 1]

var html = rehype()
    .stringify({ type: 'root', children: between(parent, start, end) })
    .toString()

console.log(html)
```

results in

```html
<span class="token keyword">var</span> a <span class="token operator">=</span>
```
The unist [docs](https://github.com/syntax-tree/unist) have more information on utilities like [unist-util-find](https://github.com/blahah/unist-util-find) and theres even a [gitter](https://gitter.im/syntax-tree/Lobby) channel.

**Comment by montogeek** [comment]
Thank you!
