### ISSUE TITLE
Last node is missing

### ISSUE THREAD

**Issue by KazimirPodolski** [mrzmmr/unist-util-find-all-between#6]
`findAllBetween` does not include last node which I guess is unexpected and not mentioned in documentation.

I think even the example is misleading because it misses "." at the end.

It is also inconvenient when used with node rather than index because you have to switch to index syntax anyway even when you already have second node.

**Comment by mrzmmr** [comment]
`findAllBetween` shouldn't include the `end` or `start` node passed as arguments, just all nodes that pass `test` between `start` and `end`, similar to [unist-util-find-all-after](https://github.com/syntax-tree/unist-util-find-all-after#api).  The example in the readme isn't correct in its output either way though theres still an issue. I'll fix the readme and make a more clear documentation, and fix to make passing a node as an argument more convenient. Thanks for the issue!
