### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by Roang-zero1** [mrzmmr/unist-util-find-all-between#8]
I would be willing to add types for this module.
In order to use dtslint I would have to create a local bundle.

My idea is to align the build pipeline with [syntax-tree/unist-util-find-all-after](https://github.com/syntax-tree/unist-util-find-all-after).

With this the local module can be used to test the types correctly.

**Comment by mrzmmr** [comment]
@Roang-zero1  Sorry took so long to respond. If your still interested in submitting a pull request I'll look it over :)

**Comment by Roang-zero1** [comment]
Great, it will probably take some time, but I will look into it.
